global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'async-job-engine'
    metrics_path: '/async-job-engine/actuator/prometheus'
    static_configs:
      - targets: ['asyncjobengine-app:8080']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'async-job-engine'
